version: '3'
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./database:/app/database
#        depends_on:
#          - worker
#          - redis
#    worker:
#        build:
#          context: