version: '3'
services:
    webapp:
        build: .
        restart: always
        environment:
          - CELERY_BROKER_URL=redis://:Th3R34lP4ssw0rd@redis:6379/0
          - CELERY_RESULT_BACKEND=redis://:Th3R34lP4ssw0rd@redis:6379/1
          - FLASK_APP=run.py
          - FLASK_ENV=development
        ports:
            - "8000:8000"
        volumes:
          - ./:/app
        user: automarked
        depends_on:
          - worker
          - redis
    worker:
        build: .
        hostname: "worker"
        environment:
          - CELERY_BROKER_URL=redis://:Th3R34lP4ssw0rd@redis:6379/0
          - CELERY_RESULT_BACKEND=redis://:Th3R34lP4ssw0rd@redis:6379/1
          - FLOWER_PORT=8888
        ports:
          - "8888:8888"
        volumes:
          - ./:/app
        user: automarked
        command: [ "worker" ]
        depends_on:
          - redis
    redis:
      image: redis
      ports:
        - "6379:6379"
      command: redis-server --requirepass Th3R34lP4ssw0rd
      sysctls:
        - net.core.somaxconn=512