version: '3'
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./database:/app/database
        depends_on:
          - worker
          - redis
    worker:
        build: .
        depends_on:
          - redis
    monitor:
        build: .
        ports:
          - "8001:8001"
        entrypoint: entrypoint_flower.sh
        depends_on:
          - redis
    redis:
      image: redis